version: '3'
services:
  cassandra1:
    image: mycas
    deploy:
      replicas: 1
      placement:
        constraints:
          [node.hostname == cassandra1]
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    environment:
      CASSANDRA_BROADCAST_ADDRESS: 10.0.0.48
      CASSANDRA_LISTEN_ADDRESS: 10.0.0.48
      CASSANDRA_SEEDS:
    volumes:
    - volume1:/var/lib/cassandra
    - casconfig1:/etc/cassandra
    ports:
    - "7000"
    - "7199"
    - "9160"
    - "9042"
    networks:
      default:
  cassandra2:
    image: mycas
    deploy:
      replicas: 1
      placement:
        constraints:
          [node.hostname == cassandra2]
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    environment:
      #CASSANDRA_BROADCAST_ADDRESS: 192.168.99.102
      #CASSANDRA_LISTEN_ADDRESS: 10.0.0.4
      CASSANDRA_SEEDS: 10.0.0.48
    depends_on:
      - cassandra-1
    volumes:
    - volume2:/var/lib/cassandra
    - casconfig2:/etc/cassandra
    ports:
    - "7000"
    - "7199"
    - "9160"
    - "9042"
    networks:
      default:
volumes:
  volume1:
    external: true
  volume2:
    external: true
  casconfig1:
  casconfig2:
networks:
  default:
    external:
       name: cassandra-net